name: eslint-static-analysis 
on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'main'

jobs:
  ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Project & Test
        run: |
          npm install .
          npx next lint 